In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [76]:
data=pd.read_csv("messy_data.csv")
data=pd.DataFrame(data)
print(data)

      Name   Age  Gender    Income      City Date_of_Joining
0    Alice  25.0  Female   50000.0  New York      2020-06-10
1      Bob   NaN    Male   60000.0       NaN      2021-05-20
2  Charlie  30.0     NaN   80000.0    Boston      2019-08-15
3    David  40.0    Male       NaN  New York      2020-01-30
4      Eva  29.0  Female   72000.0   Chicago             NaN
5    Alice  25.0  Female   50000.0  New York      2020-06-10
6    Frank  38.0    Male  900000.0    Boston      2018-03-10

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             7 non-null      object
 1   Age              6 non-null      float64
 2   Gender           6 non-null      object
 3   Income           6 non-null      float64
 4   City             6 non-null      object
 5   Date_of_Joining  6 non-null      object
dtypes: float64(2), object(4)
memory usage: 468.0+ bytes

In [42]:
data.sample()

    Name   Age Gender  Income      City Date_of_Joining
3  David  40.0   Male     NaN  New York      2020-01-30

In [43]:
data.describe()

             Age         Income
count   6.000000       6.000000
mean   31.166667  202000.000000
std     6.431692  342157.858305
min    25.000000   50000.000000
25%    26.000000   52500.000000
50%    29.500000   66000.000000
75%    36.000000   78000.000000
max    40.000000  900000.000000

In [44]:
data.shape

(7, 6)

In [45]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
dtype: bool

In [46]:
data.sort_values(by="Income",ascending=True)

      Name   Age  Gender    Income      City Date_of_Joining
0    Alice  25.0  Female   50000.0  New York      2020-06-10
5    Alice  25.0  Female   50000.0  New York      2020-06-10
1      Bob   NaN    Male   60000.0       NaN      2021-05-20
4      Eva  29.0  Female   72000.0   Chicago             NaN
2  Charlie  30.0     NaN   80000.0    Boston      2019-08-15
6    Frank  38.0    Male  900000.0    Boston      2018-03-10
3    David  40.0    Male       NaN  New York      2020-01-30

In [47]:
# data.sum()

In [48]:
data.isnull()

    Name    Age  Gender  Income   City  Date_of_Joining
0  False  False   False   False  False            False
1  False   True   False   False   True            False
2  False  False    True   False  False            False
3  False  False   False    True  False            False
4  False  False   False   False  False             True
5  False  False   False   False  False            False
6  False  False   False   False  False            False

In [49]:
data.isnull().sum()

Name               0
Age                1
Gender             1
Income             1
City               1
Date_of_Joining    1
dtype: int64

In [50]:
data.duplicated().sum()

np.int64(1)

In [51]:
# removing duplicates and null values
# handling null values 
# 1. drop values using-
#        data.dropna(inplace=True)
# 2. replace values-
#        numerical columns>>>median
#        categorical columns>>>mode

In [52]:
print(data)

      Name   Age  Gender    Income      City Date_of_Joining
0    Alice  25.0  Female   50000.0  New York      2020-06-10
1      Bob   NaN    Male   60000.0       NaN      2021-05-20
2  Charlie  30.0     NaN   80000.0    Boston      2019-08-15
3    David  40.0    Male       NaN  New York      2020-01-30
4      Eva  29.0  Female   72000.0   Chicago             NaN
5    Alice  25.0  Female   50000.0  New York      2020-06-10
6    Frank  38.0    Male  900000.0    Boston      2018-03-10

In [53]:
data["Age"].fillna(data["Age"].median(),inplace=True)
data["Income"].fillna(data["Income"].median(),inplace=True)

C:\Users\infos\AppData\Local\Temp\ipykernel_26584\752014359.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].median(),inplace=True)
C:\Users\infos\AppData\Local\Temp\ipykernel_26584\752014359.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Income"].fillna(data["Income"].median(),inplace=True)

In [54]:
print(data)

      Name   Age  Gender    Income      City Date_of_Joining
0    Alice  25.0  Female   50000.0  New York      2020-06-10
1      Bob  29.5    Male   60000.0       NaN      2021-05-20
2  Charlie  30.0     NaN   80000.0    Boston      2019-08-15
3    David  40.0    Male   66000.0  New York      2020-01-30
4      Eva  29.0  Female   72000.0   Chicago             NaN
5    Alice  25.0  Female   50000.0  New York      2020-06-10
6    Frank  38.0    Male  900000.0    Boston      2018-03-10

In [55]:
data["Age"].fillna(data["Age"].mean(),inplace=True)
data["Income"].fillna(data["Income"].mean(),inplace=True)

C:\Users\infos\AppData\Local\Temp\ipykernel_26584\2918219436.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].mean(),inplace=True)
C:\Users\infos\AppData\Local\Temp\ipykernel_26584\2918219436.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Income"].fillna(data["Income"].mean(),inplace=True)

In [56]:
print(data)

      Name   Age  Gender    Income      City Date_of_Joining
0    Alice  25.0  Female   50000.0  New York      2020-06-10
1      Bob  29.5    Male   60000.0       NaN      2021-05-20
2  Charlie  30.0     NaN   80000.0    Boston      2019-08-15
3    David  40.0    Male   66000.0  New York      2020-01-30
4      Eva  29.0  Female   72000.0   Chicago             NaN
5    Alice  25.0  Female   50000.0  New York      2020-06-10
6    Frank  38.0    Male  900000.0    Boston      2018-03-10

In [57]:
data.head(7)

      Name   Age  Gender    Income      City Date_of_Joining
0    Alice  25.0  Female   50000.0  New York      2020-06-10
1      Bob  29.5    Male   60000.0       NaN      2021-05-20
2  Charlie  30.0     NaN   80000.0    Boston      2019-08-15
3    David  40.0    Male   66000.0  New York      2020-01-30
4      Eva  29.0  Female   72000.0   Chicago             NaN
5    Alice  25.0  Female   50000.0  New York      2020-06-10
6    Frank  38.0    Male  900000.0    Boston      2018-03-10

In [81]:
print(data["Gender"].mode())

0    Female
1      Male
Name: Gender, dtype: object

In [82]:
print(data["City"].mode())

0    New York
Name: City, dtype: object

In [83]:
data["Gender"].fillna(data["Gender"].mode()[0],inplace=True)
data["City"].fillna(data["City"].mode()[0],inplace=True)
data["Date_of_Joining"].fillna("01-01-2020",inplace=True)
print(data)

      Name   Age  Gender    Income      City Date_of_Joining
0    Alice  25.0  Female   50000.0  New York      2020-06-10
1      Bob   NaN    Male   60000.0  New York      2021-05-20
2  Charlie  30.0  Female   80000.0    Boston      2019-08-15
3    David  40.0    Male       NaN  New York      2020-01-30
4      Eva  29.0  Female   72000.0   Chicago      01-01-2020
6    Frank  38.0    Male  900000.0    Boston      2018-03-10

C:\Users\infos\AppData\Local\Temp\ipykernel_26584\3798706705.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Gender"].fillna(data["Gender"].mode()[0],inplace=True)
C:\Users\infos\AppData\Local\Temp\ipykernel_26584\3798706705.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["City"].fillna(data["City"].mode()[0],inplace=True)

In [84]:
data.drop_duplicates(inplace=True)
data.head(7)

      Name   Age  Gender    Income      City Date_of_Joining
0    Alice  25.0  Female   50000.0  New York      2020-06-10
1      Bob   NaN    Male   60000.0  New York      2021-05-20
2  Charlie  30.0  Female   80000.0    Boston      2019-08-15
3    David  40.0    Male       NaN  New York      2020-01-30
4      Eva  29.0  Female   72000.0   Chicago      01-01-2020
6    Frank  38.0    Male  900000.0    Boston      2018-03-10

In [86]:
data["Date_of_Joining"]=pd.to_datetime(data["Date_of_Joining"])
data["Gender"]=data["Gender"].astype("category")
data.info()

ValueError: time data "01-01-2020" doesn't match format "%Y-%m-%d", at position 4. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [63]:
Q1=data["Income"].quantile(0.75)
Q3=data["Income"].quantile(0.75)
IQR=Q3-Q1
print(Q1,Q3,IQR)

78000.0 78000.0 0.0

In [64]:
data=(data["Income"]>Q1-1.5*IQR)&(data["Income"]<Q3+1.5*IQR)
print(data)

0    False
1    False
2    False
3    False
4    False
6    False
Name: Income, dtype: bool

In [69]:
data=pd.get_dummies(data,columns=["City"],drop_first=True,dtype=int)
print(data)

      Name   Age  Gender    Income Date_of_Joining  City_Chicago  \
0    Alice  25.0  Female   50000.0      2020-06-10             0
1      Bob   NaN    Male   60000.0      2021-05-20             0
2  Charlie  30.0     NaN   80000.0      2019-08-15             0
3    David  40.0    Male       NaN      2020-01-30             0
4      Eva  29.0  Female   72000.0             NaN             1
5    Alice  25.0  Female   50000.0      2020-06-10             0
6    Frank  38.0    Male  900000.0      2018-03-10             0

   City_New York
0              1
1              0
2              0
3              1
4              0
5              1
6              0

In [70]:
data.head()

      Name   Age  Gender   Income Date_of_Joining  City_Chicago  City_New York
0    Alice  25.0  Female  50000.0      2020-06-10             0              1
1      Bob   NaN    Male  60000.0      2021-05-20             0              0
2  Charlie  30.0     NaN  80000.0      2019-08-15             0              0
3    David  40.0    Male      NaN      2020-01-30             0              1
4      Eva  29.0  Female  72000.0             NaN             1              0

In [72]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Gender"]=le.fit_transform(data["Gender"])

In [74]:
data.head(7)

      Name   Age  Gender   Income Date_of_Joining  City_Chicago  City_New York
0    Alice  25.0       0  50000.0      2020-06-10             0              1
1      Bob   NaN       1  60000.0      2021-05-20             0              0
2  Charlie  30.0       2  80000.0      2019-08-15             0              0
3    David  40.0       1      NaN      2020-01-30             0              1
4      Eva  29.0       0  72000.0             NaN             1              0

In [90]:
from sklearn.preprocessing import StandardScaler
st=StandardScaler()
data[["Age"]]=st.fit_transform(data[["Age"]])
data[["Income"]]=st.fit_transform(data[["Income"]])

In [92]:
data.head(7)

      Name       Age  Gender    Income      City Date_of_Joining
0    Alice -1.303269  Female -0.546179  New York      2020-06-10
1      Bob       NaN    Male -0.516235  New York      2021-05-20
2  Charlie -0.422682  Female -0.456347    Boston      2019-08-15
3    David  1.338493    Male       NaN  New York      2020-01-30
4      Eva -0.598799  Female -0.480302   Chicago      01-01-2020
6    Frank  0.986258    Male  1.999062    Boston      2018-03-10

In [93]:
plt.scatter(data["Income"],data["Purchased"])

KeyError: 'Purchased'