In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("customers_data.csv")
data=pd.DataFrame(data)

In [3]:
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [4]:
data.head()

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
0,1001,Rahul,41.0,Male,Delhi,99579.0,99.0,Yes
1,1002,Priya,55.0,Female,Bangalore,15255.0,44.0,Yes
2,1003,Neha,45.0,Female,Delhi,16502.0,51.0,Yes
3,1004,Aman,38.0,Female,Kolkata,85192.0,19.0,Yes
4,1005,Rahul,35.0,Female,Kolkata,80424.0,NaN,No

In [5]:
data.tail()

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
3045,1085,Neha,58.0,Female,Bangalore,421950.0,9.0,Yes
3046,1290,Arjun,31.0,Female,Mumbai,49948.0,98.0,Yes
3047,3016,Aman,52.0,Male,Bangalore,90583.0,90.0,No
3048,2409,Karan,57.0,Female,Bangalore,55910.0,14.0,Yes
3049,3607,Riya,NaN,Female,Delhi,67474.0,79.0,No

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3050 entries, 0 to 3049
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     3050 non-null   int64
 1   Name            3050 non-null   object
 2   Age             2896 non-null   float64
 3   Gender          3050 non-null   object
 4   City            2897 non-null   object
 5   Income          2897 non-null   float64
 6   Spending_Score  2899 non-null   float64
 7   Purchased       3050 non-null   object
dtypes: float64(3), int64(1), object(4)
memory usage: 190.8+ KB

In [9]:
data.sample()

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
2908,3909,Arjun,55.0,Female,Bangalore,90396.0,69.0,Yes

In [10]:
data.describe()

       Customer_ID          Age         Income  Spending_Score
count  3050.000000  2896.000000    2897.000000     2899.000000
mean   2501.971803    38.573895   60570.926821       49.411176
std     865.955930    11.897028   57280.117599       28.829117
min    1001.000000    18.000000   15005.000000        1.000000
25%    1752.250000    29.000000   34622.000000       24.000000
50%    2502.500000    39.000000   57287.000000       50.000000
75%    3252.750000    49.000000   78226.000000       74.000000
max    4000.000000    59.000000  960080.000000       99.000000

In [11]:
data.shape

(3050, 8)

In [12]:
data.isnull()

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...
3045,False,False,False,False,False,False,False,False
3046,False,False,False,False,False,False,False,False
3047,False,False,False,False,False,False,False,False
3048,False,False,False,False,False,False,False,False
3049,False,False,True,False,False,False,False,False

In [13]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3045    False
3046     True
3047     True
3048     True
3049     True
Length: 3050, dtype: bool

In [14]:
data.sort_values(by="Spending_Score", ascending=True)

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
2466,3467,Rahul,53.0,Male,Bangalore,48069.0,1.0,Yes
477,1478,Simran,43.0,Male,Bangalore,19830.0,1.0,No
492,1493,Neha,59.0,Female,Kolkata,44203.0,1.0,Yes
2901,3902,Neha,41.0,Male,Lucknow,47286.0,1.0,Yes
2270,3271,Neha,57.0,Female,Lucknow,98301.0,1.0,Yes
...,...,...,...,...,...,...,...,...
2891,3892,Arjun,53.0,Female,Mumbai,56277.0,NaN,No
2918,3919,Sneha,24.0,Male,Bangalore,99084.0,NaN,Yes
2926,3927,Neha,57.0,Female,Kolkata,43793.0,NaN,Yes
2989,3990,Arjun,NaN,Female,Delhi,16067.0,NaN,No
3008,3218,Aman,27.0,Female,Delhi,45624.0,NaN,No

In [15]:
data.sort_values(by="Income", ascending=True)

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
2330,3331,Vikas,20.0,Male,Kolkata,15005.0,35.0,Yes
1083,2084,Arjun,40.0,Female,Lucknow,15015.0,39.0,Yes
2541,3542,Neha,39.0,Female,Delhi,15026.0,37.0,No
1671,2672,Riya,49.0,Male,Kolkata,15045.0,52.0,Yes
1038,2039,Aman,55.0,Female,Bangalore,15048.0,15.0,No
...,...,...,...,...,...,...,...,...
2978,3979,Simran,46.0,Female,Mumbai,NaN,43.0,No
2981,3982,Priya,24.0,Male,Lucknow,NaN,3.0,No
3011,2925,Priya,19.0,Female,Kolkata,NaN,50.0,No
3014,1550,Aman,NaN,Male,Mumbai,NaN,86.0,No
3019,1860,Simran,NaN,Female,Lucknow,NaN,98.0,No

In [16]:
data.isnull().sum()

Customer_ID         0
Name                0
Age               154
Gender              0
City              153
Income            153
Spending_Score    151
Purchased           0
dtype: int64

In [17]:
data.duplicated().sum()

np.int64(48)

In [18]:
print(data)

      Customer_ID   Name   Age  Gender       City    Income  Spending_Score  \
0            1001  Rahul  41.0    Male      Delhi   99579.0            99.0
1            1002  Priya  55.0  Female  Bangalore   15255.0            44.0
2            1003   Neha  45.0  Female      Delhi   16502.0            51.0
3            1004   Aman  38.0  Female    Kolkata   85192.0            19.0
4            1005  Rahul  35.0  Female    Kolkata   80424.0             NaN
...           ...    ...   ...     ...        ...       ...             ...
3045         1085   Neha  58.0  Female  Bangalore  421950.0             9.0
3046         1290  Arjun  31.0  Female     Mumbai   49948.0            98.0
3047         3016   Aman  52.0    Male  Bangalore   90583.0            90.0
3048         2409  Karan  57.0  Female  Bangalore   55910.0            14.0
3049         3607   Riya   NaN  Female      Delhi   67474.0            79.0

     Purchased
0          Yes
1          Yes
2          Yes
3          Yes
4           No
...        ...
3045       Yes
3046       Yes
3047        No
3048       Yes
3049        No

[3050 rows x 8 columns]

In [19]:
data["Age"].fillna(data["Age"].median(),inplace=True)
data["Income"].fillna(data["Income"].median())
data["Spending_Score"].fillna(data["Spending_Score"].median())
data["City"].fillna(data["City"].mode()[0])
print(data)

      Customer_ID   Name   Age  Gender       City    Income  Spending_Score  \
0            1001  Rahul  41.0    Male      Delhi   99579.0            99.0
1            1002  Priya  55.0  Female  Bangalore   15255.0            44.0
2            1003   Neha  45.0  Female      Delhi   16502.0            51.0
3            1004   Aman  38.0  Female    Kolkata   85192.0            19.0
4            1005  Rahul  35.0  Female    Kolkata   80424.0             NaN
...           ...    ...   ...     ...        ...       ...             ...
3045         1085   Neha  58.0  Female  Bangalore  421950.0             9.0
3046         1290  Arjun  31.0  Female     Mumbai   49948.0            98.0
3047         3016   Aman  52.0    Male  Bangalore   90583.0            90.0
3048         2409  Karan  57.0  Female  Bangalore   55910.0            14.0
3049         3607   Riya  39.0  Female      Delhi   67474.0            79.0

     Purchased
0          Yes
1          Yes
2          Yes
3          Yes
4           No
...        ...
3045       Yes
3046       Yes
3047        No
3048       Yes
3049        No

[3050 rows x 8 columns]

C:\Users\infos\AppData\Local\Temp\ipykernel_17144\2434973497.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].median(),inplace=True)

In [20]:
data.head()

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
0,1001,Rahul,41.0,Male,Delhi,99579.0,99.0,Yes
1,1002,Priya,55.0,Female,Bangalore,15255.0,44.0,Yes
2,1003,Neha,45.0,Female,Delhi,16502.0,51.0,Yes
3,1004,Aman,38.0,Female,Kolkata,85192.0,19.0,Yes
4,1005,Rahul,35.0,Female,Kolkata,80424.0,NaN,No

In [21]:
data.drop_duplicates(inplace=True)

In [22]:
data.duplicated().sum()

np.int64(0)

In [23]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Gender"]=le.fit_transform(data['Gender'])
data.head()

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
0,1001,Rahul,41.0,1,Delhi,99579.0,99.0,Yes
1,1002,Priya,55.0,0,Bangalore,15255.0,44.0,Yes
2,1003,Neha,45.0,0,Delhi,16502.0,51.0,Yes
3,1004,Aman,38.0,0,Kolkata,85192.0,19.0,Yes
4,1005,Rahul,35.0,0,Kolkata,80424.0,NaN,No

In [24]:
data["Purchased"]=data["Purchased"].astype("category")

In [25]:
print(data)

      Customer_ID    Name   Age  Gender       City    Income  Spending_Score  \
0            1001   Rahul  41.0       1      Delhi   99579.0            99.0
1            1002   Priya  55.0       0  Bangalore   15255.0            44.0
2            1003    Neha  45.0       0      Delhi   16502.0            51.0
3            1004    Aman  38.0       0    Kolkata   85192.0            19.0
4            1005   Rahul  35.0       0    Kolkata   80424.0             NaN
...           ...     ...   ...     ...        ...       ...             ...
2997         3998   Arjun  38.0       0     Mumbai   72295.0            87.0
2998         3999  Simran  39.0       1     Mumbai   48939.0            31.0
2999         4000   Rahul  52.0       0    Lucknow   63599.0            36.0
3029         3795   Vikas  26.0       0  Bangalore   93798.0            70.0
3045         1085    Neha  58.0       0  Bangalore  421950.0             9.0

     Purchased
0          Yes
1          Yes
2          Yes
3          Yes
4           No
...        ...
2997       Yes
2998        No
2999        No
3029       Yes
3045       Yes

[3002 rows x 8 columns]

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3002 entries, 0 to 3045
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     3002 non-null   int64
 1   Name            3002 non-null   object
 2   Age             3002 non-null   float64
 3   Gender          3002 non-null   int64
 4   City            2852 non-null   object
 5   Income          2852 non-null   float64
 6   Spending_Score  2852 non-null   float64
 7   Purchased       3002 non-null   category
dtypes: category(1), float64(3), int64(2), object(2)
memory usage: 190.7+ KB

In [27]:
data.head()

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
0,1001,Rahul,41.0,1,Delhi,99579.0,99.0,Yes
1,1002,Priya,55.0,0,Bangalore,15255.0,44.0,Yes
2,1003,Neha,45.0,0,Delhi,16502.0,51.0,Yes
3,1004,Aman,38.0,0,Kolkata,85192.0,19.0,Yes
4,1005,Rahul,35.0,0,Kolkata,80424.0,NaN,No

In [28]:
#using IQR (interquartile range) method
Q1=data['Income'].quantile(0.25)
Q2=data['Income'].quantile(0.75)
IQR=Q2-Q1
print(Q1,Q2,IQR)
print(data["Income"])

34588.0 78251.25 43663.25
0        99579.0
1        15255.0
2        16502.0
3        85192.0
4        80424.0
          ...
2997     72295.0
2998     48939.0
2999     63599.0
3029     93798.0
3045    421950.0
Name: Income, Length: 3002, dtype: float64

In [ ]:
data=pd.get_dummies(data,columns=['City'], drop_first=True, dtype=int)